### ISSUE TITLE
$ActionUrl in Emails has wrong/old address

### ISSUE THREAD

**Issue by Sartharon** [pterodactyl/panel#2189]
**Background (please complete the following information):**
* Panel
* Version of Panel: 0.7.17 `PHP 7.2.32-1`
* Server's OS: Ubuntu 18.04 LTS

**Describe the bug**
Creating a user without a password sends out an email to the user with the wrong/old address to set a password

**To Reproduce**
Change the domain of the panel (i.e moving to a new domain name).
Change domain in .env (to reflect this change of domain)
Create a new user without a password
User recieves an email with and address pointing to the old domain

**Expected behavior**
$actionurl should be fetched from .env (APP_URL) and thus have the correct baseurl in the mail

**Comment by parkervcp** [comment]
Last I checked laravel/php doesn't actually update the variables in realtime unless configured to do so.

We call this out in the docs. <https://pterodactyl.io/panel/0.7/configuration.html>

**Comment by Sartharon** [comment]
Alright I seem to have missed that.
But still shouldnt the we somehow have a solution for this issue
Seems like it is very tedious to change that
Maybe a setting for the panel in the setting section?

**Comment by TrixterTheTux** [comment]
You need to restart pteroq for it to get the information of new panel URL, as it's a long-running process which caches that data only on startup.

**Comment by Sartharon** [comment]
I got it to change thanks to @parkervcp
But i still feel some of the settings in the .env could have an option inside the panel. (i.e Trusted  Proxies, App Url, Timezone)
Since the SMTP settings reside there, which also have an option inside the panel. Settings are all over (Database all, but only some configurable trough the panel ||| .env some but do not reflect the changes you made throught he panel i.e smtp settings)

**Comment by DaneEveritt** [comment]
I'm guessing you cached your config. `php artisan cache:clear` should fix it.

**Comment by Sartharon** [comment]
Sadly this didnt work either

Incase my order of operation is incorrect here is what I did:

1. change `APP_URL`
2. set `APP_ENVIRONMENT_ONLY` to `true`
3. run `php /var/www/pterodactyl/artisan cache:clear`
4. run `sudo service pteroq restart`


creating a new user still gets an email with the old ip instead of the new domain

**Comment by DaneEveritt** [comment]
I don't know what to tell you, it works fine for basically everyone else and I've never seen this fail for someone like this. We don't even use the database to store the URL so that setting (`APP_ENVIRONMENT_ONLY`) doesn't really even matter. If it is still sending the old IP address then:

1. Your `pteroq` instance is pointing to an entirely different location and reading a different configuration.
2. You have a hard-coded value somewhere causing issues.

You can confirm either of these by changing `'url' => env('APP_URL')` in the `config/app.php` file to be a hard-coded URL and restarting the queue worker. If the emails still send with the wrong URL then I don't know what to tell you.

Suffice to say this is not a bug with this application, it gets reported every few months and it is always some system configuration/cached config file issue.

**Comment by DaneEveritt** [comment]
Also realizing it should be `config:clear` and not `cache:clear` my bad.

**Comment by Sartharon** [comment]
Thanks for trying to help, I appreciate it

Seems like nothing works :

1. `env | APP_URL` is empty
2. `grep -iRl "<oldIP>" /var/www/pterodactyl`  returns empty handed too (so nothing hardcorded)
3. `pteroq` is pointing to the panels artisan (/var/www/pterodactyl/artisan and is just copy paste from [https://pterodactyl.io/panel/0.7/getting_started.html#create-queue-worker](url))

 
I will post an update here incase I find the culprit so i can help others

**Comment by DaneEveritt** [comment]
Did you try the corrected command I posted after closing?

**Comment by Sartharon** [comment]
Sadly yes but it didnt change the outcome
As you said there might be something wrong on my end
I'll try to figure it out

**Comment by Sartharon** [comment]
Alright after carefully reading through the documentaion I fixed it by running
`php artisan p:environment:setup`
again which worked.
