### ISSUE TITLE
Error when migrating db to a new panel install

### ISSUE THREAD

**Issue by Kriiiiiiiz** [pterodactyl/panel#3231]
**Background:**
* Panel or Daemon: Panel
* Version of Panel/Daemon: Working on 1.2.2, not working on 1.3.2
* Server's OS: Ubuntu Server 20.04
* Your Computer's OS & Browser: MacOS, Safari

**Describe the bug**
I've installed a new clean panel (1.3.2), copied my old .env file from old panel (1.2.2) and set up same database.
New panel prints this in logs: http://bin.ptdl.co/ofsrp

(Starting up again my old panel everything works ok but not in my new Install.)

**To Reproduce**
I dont really know how to reproduce it :(

**Expected behavior**
Schedules should be the same in both panels right ? As i am using same db and encryption key.

My chedules on 1.2.2
![unknown](https://user-images.githubusercontent.com/13300613/112751206-f61b0b80-8fcc-11eb-8125-c65fd1e6d945.png)

My schedules on 1.3.2
![unknown-1](https://user-images.githubusercontent.com/13300613/112751236-2367b980-8fcd-11eb-8498-2acc03f0e9b9.png)

**Comment by trenutoo** [comment]
This should be fixed in 1.3.2 when seeding the database, you can also resolve the issue with the following commands:

```
mysql -u root -p
UPDATE panel.schedules SET cron_month = '*';
```

**Comment by Kriiiiiiiz** [comment]
I get this:

![Screenshot_2021-03-28_at_13 01 45](https://user-images.githubusercontent.com/13300613/112752879-6a59ad00-8fd5-11eb-88da-b823469e43a4.png)


And do this ( php artisan migrate --seed --force ) erase the db and generates a new one ?

**Comment by Kriiiiiiiz** [comment]
??

**Comment by DaneEveritt** [comment]
This is not a bug that still exists and you were provided a command to fix it.

**Comment by Kriiiiiiiz** [comment]
I know, the issue comes when I execute the command... It doesn't fix it
