### ISSUE TITLE
Can't turn on server without restarting wings: another power action is currently being processed

### ISSUE THREAD

**Issue by AV3RG** [pterodactyl/panel#3903]
# STOP! Read this before responding! :warning:

**Please do not post any replies that do not contain any actual logs or don't contribute anything to this issue. If you have a temporary fix like cronjob keep that to yourself as it will do nothing to fix the underlying issue**

If you're going to respond to this issue, _please_ do not respond to say "+1" or "I also have this issue." If you are responding, please include all relevant information, including the output of `wings diagnostics` and your full wings log if possible. Make sure your system is running with `--debug` or `debug: true` (in the `config.yml`) before submitting your logs.

Please clearly identify timestamps and servers that are affected, we have limited time to work on this project, trying to identify or hunt down this bug is not feasible without clear and detailed reported.

## Update: Potential Fix
See [this comment](https://github.com/pterodactyl/panel/issues/3903#issuecomment-1021574549) for details.

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.

### Current Behavior

Sometimes while restarting or stopping the server, wings show that the server is stuck in offline mode like this

![image](https://user-images.githubusercontent.com/76780190/150559868-e6391622-6dc9-4cf0-aa26-859527d61b10.png)

It still shows the time next to the online status

When it is stuck like that you cant start/restart the server. Any attempts to do so show this on the console constantly (not due to spamming power buttons)

![image](https://user-images.githubusercontent.com/76780190/150560182-d17f68e8-d763-403e-844f-ac69a89adcba.png)

However, if you restart wings the server returns to a normal offline state and you can start it normally

### Expected Behavior

Normally the time does not show up (when it's not stuck) and you can start the server normally

![image](https://user-images.githubusercontent.com/76780190/150560051-467edaee-fa9a-41ac-b1f0-c99a7eb935c3.png)

### Steps to Reproduce

It does not happen every time. There are no particular steps to reproduce, happens when restarting or stopping the server.
I have seen many facing the same issue in the pterodactyl discord

### Panel Version

1.7.0

### Wings Version

1.5.5

**Comment by mundotv789123** [comment]
I have the some problem!

**Comment by lstefan1520** [comment]
Seeing the same issue. 

Occurred after upgrade to latest wings. Reverting fixes the issue. 
![0EE5B75B-4AAF-418B-9F69-589196CE1029](https://user-images.githubusercontent.com/44349634/150609921-bbcabd17-ca91-42bd-8daa-e5005bfbb648.png)

**Comment by nikrozman21** [comment]
I can confirm the same. Getting the same error as Mark above me, compiled on Go 1.17.5.
Both the panel and wings otherwise are up to date as of writing this comment.

**Comment by Mutex21** [comment]
I’ve the same problem after updating to .55 version.

**Comment by iLucasUS** [comment]
same problem.

**Comment by Rezanans-wow** [comment]
Me can confirm too. Restart of wings help resolve it

Wings: 1.5.5
Panel: 1.6.6 (1.7.0 manually compiled)

**Comment by luizsusin** [comment]
I can confirm this problem too. Restarting wings fixes it. Started hapenning after updating to Wings 1.5.5.
Panel: 1.7.0
Wings: 1.5.5

**Comment by trenutoo** [comment]
Commenting "me too" is of no use for troubleshooting and triggers notifications for nothing. Me and Matthew spent hours trying to reproduce and identify it. 

Please provide data to reproduce and identify the issue instead. What did you do for it to happen, possible errors in wings logs, etc

**Comment by luizsusin** [comment]
> Commenting "me too" is of no use for troubleshooting and triggers notifications for nothing. Me and Matthew spent hours trying to reproduce and identify it.
> 
> Provide data to reproduce and identify the issue instead.

I appreciate the hard work you guys have done so far. Maybe the _not confirmed_ label makes people (like me) want to help by showing it's a thing, without the intention of triggering notification for nothing.

For additional info which I haven't seen in any other comment, it has happened to me with a scheduled power action, so this might not have a browser influence. My OS is Ubuntu Server 20.04.3.

**Comment by NoSharp** [comment]
From my experience today, I pressed stop then kill within a second from one another and it managed to cause this.

EDIT:
Another bit of information that might be useful:
when trying to stop/start wings via systemctl stop wings, It wasn't actually stopping the process/unbinding the port.
The way around was using lsof and manually using `kill` to kill the process.

**Comment by Brandin** [comment]
This issue began occurring on my installation after the upgrade to 1.5.4 and subsequently to 1.5.5. The server is on Ubuntu 20.04.1 and fully up to date. Restarting wings, as mentioned, resolves the issue for me, but sometimes I'll need to kill it or reboot the server. Can you let me know what kind of logs would be useful so I can help supply them? I'd be happy to!

**Comment by iLucasUS** [comment]
restarting wings temporarily resolves the issue. after a while he goes back to saying that he already has a power action in progress. No error log is being generated. shouldn't the solution be to think of a more efficient way to capture if the service is actually running or not?

**Comment by iLucasUS** [comment]
restarting wings temporarily solves the problem, but after a while it says that it already has a power action in progress. No error log is being generated. shouldn't the solution be to think of a more efficient way to capture if the service is actually running or not?

**Comment by LucidAPs** [comment]
Same here, issue happened with the 1.5.4-1.5.5 upgrade, I am also on Ubuntu 20.04.1 but I am not using any scheduler features. The issue happens after I leave the servers running for a day or so, the servers have activity with large amount of players playing (if it might matter). So after a day when I want to shutdown, everything seems normal, but when I press stop, wings stops updating the consoles and all other server indicators, and I need to keep reloading the page to see what happens. When they are all stopped and I try to start them again, the error message appears and I need to restart wings.

**Comment by DaneEveritt** [comment]
Please try downloading and running the following build: https://github.com/pterodactyl/wings/actions/runs/1736581488

Click on the correct artifact for your processor in the "Artifacts" list, and then replace your current wings binary with this one, as if it was a normal upgrade. I changed how the power actions handler works, I can't promise it actually fixes anything but it should start providing some better debugging information for me.

Make sure you have `debug: true` in your Wings config, or run with `--debug`.

@LucidAPs @iLucasUS @Brandin @NoSharp @markd69 @RohanGoyalDev

**Comment by iLucasUS** [comment]
I just installed this build, soon I'll tell you if it solved.

**Comment by iLucasUS** [comment]
not work.

**Comment by DaneEveritt** [comment]
That is not a helpful response unfortunately. Can you please provide the logs, ideally as much of them as you can, you may need to pull this from something other than the diagnostics command.

Please also clearly indicate the server UUID that was affected.

**Comment by iLucasUS** [comment]
Wings does not show any errors.

**Comment by DaneEveritt** [comment]
It wouldn't, which is why I asked for the logs because I added debugging statements for myself. :)

**Comment by iLucasUS** [comment]
![Screenshot_3](https://user-images.githubusercontent.com/53278250/150722992-6aed026a-574b-42f6-9b57-482acf482479.png)
here!!!

**Comment by iLucasUS** [comment]
This error is in version 1.5.6

**Comment by de-Rick** [comment]
Wings 1.5.6

https://ptero.co/waleqehenu.yaml

**Comment by LucidAPs** [comment]
Unfortunally, it still happens on 1.5.6.

**Comment by DaneEveritt** [comment]
> Can you please provide the logs, ideally as many of them as you can, you may need to pull this from something other than the diagnostics command.

@iLucasUS @de-Rick

Please just attach the raw log files, the diagnostics command trims the log output significantly. Additionally, please tell me what specific servers are having this issue (their specific UUID) so that when I filter down the logs I know what server to be looking at.

Thanks.

**Comment by OreQr** [comment]
![image](https://user-images.githubusercontent.com/50458706/150802158-36c1fd60-fb27-4576-b092-5a8fd4d14e8d.png)
I can't start server
EDIT: wings logs https://ptero.co/agitepycul

**Comment by patrickdeitmer** [comment]
Here you are: http://badger.alphaoperations.eu/wings20220124.log

This log contains ALL logging since the setup of wings (new setup)

The Server is running wings v1.5.5 up until Jan 23 20:03. Then it got upgraded to wings vdev-(https://github.com/pterodactyl/wings/actions/runs/1736581488 (amd64))
Debug flag has been enabled shortly before that.


Debian GNU/Linux 11
Docker version 20.10.12, build e91ed57
Panel 1.6.6

The uuid in question is 68cdca9f-44ee-40ad-8516-79fec70e4168

What else information do you need?

**Comment by Synkstar** [comment]
> ![image](https://user-images.githubusercontent.com/50458706/150802158-36c1fd60-fb27-4576-b092-5a8fd4d14e8d.png) I can't start server EDIT: wings logs https://ptero.co/agitepycul

I'm getting the same error as this now seems to happen when using a schedule but only on one server for some reason. Idk its strange. Was "another power action is being processed" before but the update changed it to this

**Comment by N3M0dropserver** [comment]
used to have an error like this:
![image](https://user-images.githubusercontent.com/45587852/150938819-aba98fd6-2c34-434f-8dc6-b2da8f1cb477.png)
then when I upgraded the wings and panel again it changed to this:
![image](https://user-images.githubusercontent.com/45587852/150939761-8780c7f3-d756-44e5-a65e-42b0239c14b1.png)
havent enabled debug sorry, will attempt to do so now and wait till it reproduces

**Comment by LucidAPs** [comment]
I think the devs might be missing the info I wrote above, that this occurs only when you leave the servers running for more then 12+ hours and system resources get used.

**Comment by N3M0dropserver** [comment]
> I think the devs might be missing the info I wrote above, that this occurs only when you leave the servers running for more then 12+ hours and system resources get used.

from what I've experienced that's not the case, the servers that have encountered this have been restarted and a few times and then have the same occurrence happen again. I fixed the issue the first time just by restarting the wings service but then I restarted one of the servers on the panel and it happened again. only somewhat got fixed when I updated both again the panel and wings

**Comment by N3M0dropserver** [comment]
heres a video I made reproducing it.
Uploading simplescreenrecorder-2022-01-25_21.38.38.mp4…

**Comment by N3M0dropserver** [comment]
Heres a video I made reproducing it:
https://user-images.githubusercontent.com/45587852/150942400-4e15a222-cba7-4b2f-bad8-44d23e20878f.mp4

**Comment by trenutoo** [comment]
> Heres a video I made reproducing it:

That's not reproducing the issue reported here, which is the lock not being released.

What you are doing is spamming power actions thus you receive the power action error. Your server still starts and stops.

**Comment by Synkstar** [comment]
Im pretty sure this problem is caused when the panel freezes due to a websocket connection write error then when someone tries to restart the server or well the schedule it gives failed to acquire exclusive lock and completely locks it up. The freezing happens when someone switches ips while using the panel.( like say when you connect to a vpn) Here are the two notable errors 
```
Stacktrace:
write tcp {redacted}:8443->{redacted}:61236: write: connection timed out
github.com/pterodactyl/wings/router/websocket.(*Handler).listenForServerEvents.func1
        /home/runner/work/wings/wings/router/websocket/listeners.go:99
github.com/pterodactyl/wings/router/websocket.(*Handler).listenForServerEvents
        /home/runner/work/wings/wings/router/websocket/listeners.go:118
github.com/pterodactyl/wings/router/websocket.(*Handler).registerListenerEvents.func1
        /home/runner/work/wings/wings/router/websocket/listeners.go:29
runtime.goexit
        /opt/hostedtoolcache/go/1.17.6/x64/src/runtime/asm_amd64.s:1581
 ```
```
ERROR: [Jan 25 06:32:32.127] error processing websocket event "set state" error=failed to acquire exclusive lock for power actions: cannot acquire a lock on the power state: already locked error_identifier=68d63a19-8ce2-40b3-9905-841ec3ed895e event=set state server=581857c2-17b5-4229-9fe0-965bf1279c40

Stacktrace:
cannot acquire a lock on the power state: already locked
github.com/pterodactyl/wings/server.(*powerLocker).Acquire
        /home/runner/work/wings/wings/server/power.go:77
github.com/pterodactyl/wings/server.(*Server).HandlePowerAction
        /home/runner/work/wings/wings/server/power.go:177
github.com/pterodactyl/wings/router/websocket.(*Handler).HandleInbound
        /home/runner/work/wings/wings/router/websocket/websocket.go:355
github.com/pterodactyl/wings/router.getServerWebsocket.func3
        /home/runner/work/wings/wings/router/router_server_ws.go:85
runtime.goexit
        /opt/hostedtoolcache/go/1.17.6/x64/src/runtime/asm_amd64.s:1581
``` 
This is most likely what is causing this issue because peoples cpu usage is frozen on the panel as well.

**Comment by DaneEveritt** [comment]
Interesting, theoretically that shouldn't make a difference because the lock should be tied to the Docker container's state (or the command being executed in Docker), and not the user's connection. Allegedly I wrote it so that if the context is canceled (e.g. the request/connection dies) the rest of the functionality should die as well, thus releasing the lock.

But thats a decent start and I can fiddle around with it more. @Synkstar are you able to reliably reproduce it in that case, just to confirm it wasn't luck of the draw? Also, @Synkstar can you include your logs so I can see the full event sequence?

**Comment by patrickdeitmer** [comment]
I am not using the panel much. Most of my cases of "unable to start" were in the morning or during the night, where I was not using the panel. Webserver logs show that my application made two calls to the API. One to stop the server, and then 15 seconds later to start. I can not proof that the application was shut down at the point when it started again.

Currently, I am running 1.5.3 at night (when I am not here, no lockups there) and 1.5.6 during the day when I can see the monitoring. I was running 1.5.3 since October on the same hardware without problems and minimum maintenance. The game I'm running in the container is the same, the application I am using to start/stop via API is the same (more or less).

**Comment by JRH-1997** [comment]
https://ptero.co/amyxahecor
Here are some logs of when the error happened and before it.

**Comment by Synkstar** [comment]
> Interesting, theoretically that shouldn't make a difference because the lock should be tied to the Docker container's state (or the command being executed in Docker), and not the user's connection. Allegedly I wrote it so that if the context is canceled (e.g. the request/connection dies) the rest of the functionality should die as well, thus releasing the lock.
> 
> But thats a decent start and I can fiddle around with it more. @Synkstar are you able to reliably reproduce it in that case, just to confirm it wasn't luck of the draw? Also, @Synkstar can you include your logs so I can see the full event sequence?

Yeah I'm able to reproduce it. The only useful things in those logs is the errors. But if I turn on debugging I get 
https://gist.github.com/Synkstar/fa505208555768b3c607eae6fce5a9df. To reproduce basically just keep changing your ip and reloading the panel and eventually it will happen. I usually like waited a bit of leaving it frozen due to the ip being changed.
Edit:
```
	if err := h.unsafeSendJson(v); err != nil {
		// Not entirely sure how this happens (likely just when there is a ton of console spam)
		// but I don't care to fix it right now, so just mask the error and throw a warning into
		// the logs for us to look into later.
		if errors.Is(err, websocket.ErrCloseSent) {
			if h.server != nil {
				h.server.Log().WithField("subsystem", "websocket").
					WithField("event", v.Event).
					Warn("failed to send event to websocket: close already sent")
			}
			return nil
		}

		return err
	}
``` 
On line 160 in websocket.go it says that im guessing this issue has something to do with that. Why is it called unsafe send json though ?!?

**Comment by nackerr** [comment]
I'm receiving this issue quite often now, and it seems after scheduled restarts. I would attach the full logs, but debug was set to false.

It just happened on uuid b2bcc205-d787-4ee7-a80c-ee05bb19e29d.

https://ptero.co/qoqecigavi

**Comment by matthewpi** [comment]
I have a new build for anyone experiencing this problem.  It changes the logic when starting a server from `create, start, attach` to `create, attach, start` (this is how the `docker run` command also works).  This build also has additional debug logs around starting and attaching to the container which should help us diagnose any further problems.

You can download the build from https://github.com/pterodactyl/wings/actions/runs/1747467060
*NOTE: You will need to be logged in to download the build artifact.*

**Comment by ProxTricky** [comment]
Same error, here's the log for the help !
Simply restarting wings do the trick for me
https://ptero.co/welymiwowi

**Comment by lstefan1520** [comment]
> I have a new build for anyone experiencing this problem. It changes the logic when starting a server from `create, start, attach` to `create, attach, start` (this is how the `docker run` command also works). This build also has additional debug logs around starting and attaching to the container which should help us diagnose any further problems.
> 
> You can download the build from https://github.com/pterodactyl/wings/actions/runs/1747467060 _NOTE: You will need to be logged in to download the build artifact._

Seeing the following error on this build. 
https://ptero.co/enibylylyb.lua

Appears not to be resolved on this build. 

Edit: sorry! Did not see the log messages on the message above

**Comment by NerdsForGaming** [comment]
Happened to me on my private host and a public one, Wings ver was 1.5.5 for my private server and the host uses 1.5.6 (idk how)
this has happened to many people that are using that public host and to me about 20times and even without pressing any buttons on the panel like doing /restart in game this thing happens
I hope i provided some info

**Comment by iLucasUS** [comment]
https://ptero.co/emoxyginov

**Comment by Synkstar** [comment]
Does anyone know what version this started happening on? I think it has something to do with how they handle websocket connections because it freezes the server console on the new version it doesn't show the write error I mentioned but the console still freezes.

**Comment by patrickdeitmer** [comment]
I am on 1.5.3 since October. Upgraded to 1.5.5 last week, due to a system
restore after hardware defect.

Downgraded now to 1.5.3. Tomorrow I’m available all day, will run 1.5.4 for
testing and will report back then.

1.5.3 no issues (related to this ticket)
1.5.4 unknown
1.5.5 lockup and wings restart required
1.5.6 lockup and wings restart required

**Comment by SRD3V** [comment]
Ladies and gentlemen.

I built a temporary fix that isn't the most optimal, but it does work. 
The trick is very simply.

The Magic word is: "CRONTAB" :-) 

Type in SSH
`crontab -e`
Add the Line on each Wing server
`0 * * * * systemctl restart wings >/dev/null 2>&`
Done!

This command automatically executes the wings restart command every hour. So you don't have to do this by hand anymore. Of course you can also play something here at the times.

**Comment by patrickdeitmer** [comment]
> Ladies and gentlemen.
> 
> I built a temporary fix that isn't the most optimal, but it does work. The trick is very simply.
> 
> The Magic word is: "CRONTAB" :-)
> 
> Type in SSH `crontab -e` Add the Line on each Wing server `0 * * * * systemctl restart wings >/dev/null 2>&` Done!
> 
> This command automatically executes the wings restart command every hour. So you don't have to do this by hand anymore. Of course you can also play something here at the times.

This is maximum a workaround. And it does create a ton of other problems. What if the lockup happens 1 minute after the hour? I have to wait for 59 minutes?

**Comment by SRD3V** [comment]
> > Ladies and gentlemen.
> > I built a temporary fix that isn't the most optimal, but it does work. The trick is very simply.
> > The Magic word is: "CRONTAB" :-)
> > Type in SSH `crontab -e` Add the Line on each Wing server `0 * * * * systemctl restart wings >/dev/null 2>&` Done!
> > This command automatically executes the wings restart command every hour. So you don't have to do this by hand anymore. Of course you can also play something here at the times.
> 
> This is maximum a workaround. And it does create a ton of other problems. What if the lockup happens 1 minute after the hour? I have to wait for 59 minutes?

[...] **__Of course you can also play something here at the times.__** [...]
[There are so many possibilities! Of course you can also have the logs read out every 5 minutes and tell the crontab at certain words to execute command XYZ... It's just about the idea and the temporary automation. Not about any scientific solutions. Please read carefully. I have over 500 clients using Pterodactyl daily. This enabled us to contain the problem and temporarily fix it.

**Comment by MonkaMaczna** [comment]
After updating wings to the newest versopn scheduled restart doesn't work.
Logs: https://ptero.co/wygamuzuha.yaml

**Comment by Synkstar** [comment]
> I am on 1.5.3 since October. Upgraded to 1.5.5 last week, due to a system
> restore after hardware defect.
> 
> Downgraded now to 1.5.3. Tomorrow I’m available all day, will run 1.5.4 for
> testing and will report back then.
> 
> 1.5.3 no issues (related to this ticket)
> 1.5.4 unknown
> 1.5.5 lockup and wings restart required
> 1.5.6 lockup and wings restart required 

The issue is still on 1.5.3. The websocket handler it seems still locks up and prevents the server from starting

**Comment by patrickdeitmer** [comment]
> 

Then maybe we are chasing different issues here. I did not experience any issues since beginning of october 2021 till 23. january 2022. Running 1.5.3 on two machines.

Updated to 1.5.5 on Jan 23 00:45:47 and have this lockups happening frequenctly. (every 2-3 hours)
Updated to the offered dev version vdev- on Jan 23 20:04:03 and continued to experience this problems.
Downgraded to 1.5.3 Jan 24 23:04:21 and have not experienced any lockups yet. (I am not talking about temp lockups due to spamming power actions). Wings did run continiously till Jan 28 09:10:21 without restarts. Thats almost 3 1/2 days.
Updated to 1.5.4 this morning at Jan 28 09:10:21 and so far had no lockups. (However I believe the timeframe is too short yet for a conclusion)

Time of writing Jan 28 13:15:01

I do not, or have almost never executed any function from the panel via a browser on a wonky connection. All commands are executed from localhost via api request to the panel api. Same goes for the console... I am reading file logs from the application running within the container, not via the webpanel.

**Comment by DaneEveritt** [comment]
This has been a long standing issue that has existed for nearly the entire existence of Wings, it just became more prevalent due to other changes that improved the consistency at which it happened.

Unless you're providing feedback about the development builds @matthewpi provided, or providing specific logs and details, please refrain from commenting on this issue. It causes excessive notification noise, and hides important details and conversations from others.

> I have a new build for anyone experiencing this problem. It changes the logic when starting a server from `create, start, attach` to `create, attach, start` (this is how the `docker run` command also works). This build also has additional debug logs around starting and attaching to the container which should help us diagnose any further problems.
> 
> You can download the build from https://github.com/pterodactyl/wings/actions/runs/1747467060 _NOTE: You will need to be logged in to download the build artifact._

**Comment by Synkstar** [comment]
I recorded a video of me reproducing the problem takes about 5 or so minutes to cause it to heppen. https://streamable.com/mp03by. Im just switching my ips using vpn connections I have basically and refreshing. Edit: seems to also happen if I change ips once and wait 5-20 minutes just tested

**Comment by Synkstar** [comment]
The issue doesn't seem to happen if you run wings behind an nginx reverse proxy on the same server/node connecting via localhost. Nginx correctly handles the websocket connections and handles the timing out so the connections get closed correctly. 
https://www.nginx.com/blog/websocket-nginx/ 
You also need to disable https on wings, set it to listen on localhost and have nginx bind to the public ip and do https. 
I did the same thing that I did in the video and it didn't happen and its been more than 30 minutes ill know for sure tomorrow if no one is having that issue. I guess by the looks of it this can be used as a temporary patch

Edit: This seems to have fixed it I haven't had this issue in 2 days used to happen daily. Id say this is the best fix here because it doesn't break at all and doesn't require you to use a cronjob

**Comment by Oliverdotdotdot** [comment]
I am having the same error on my hosting company, I have found a temporary fix until this gets resolved.

If running any Linux OS's you should be able to use cronjob's to restart wings every 5 minutes or so, that will make the servers that are unable to startup with the timer able to start up again.

**Comment by Brandin** [comment]
This issue went away for me for quite a few days, during that time:
- I made no manual/remote changes to files (all were done by the container itself, eg. log files)
- I restarted it daily via scheduled action 

Yesterday, when a number of files were changed, both by the container and myself (2 remote files changed), the scheduled restart failed as it was unable to power the server back on, with the previous error log we're presented before in this thread. I'm unsure if my diagnosis of some files being changed manually by myself aids us in any way, but I wanted to mention that this behavior occurred only after this action, and worked fine for days prior.

**Comment by DaneEveritt** [comment]
Hi all — unless you're running the latest code from `develop` or the specific build that [@matthewpi highlighted](https://github.com/pterodactyl/panel/issues/3903#issuecomment-1021574549), we don't need any more reports. We're fully aware that it is not working properly, but unless you have _consistent, reproducible_ steps for this bug, it isn't helpful for us if you keep replying to this thread.

If you encounter issues on that development build, we want to know, otherwise we believe this issue is resolved.

**Comment by EliteNover** [comment]
Still having problems on the 1.6.0 version
https://ptero.co/xanivyfofi

**Comment by BurritoWrapped** [comment]
Still having issues on the latest version that was suggested.

`ERROR: [Jan 31 12:48:07.146] error processing websocket event "set state" error=failed to acquire exclusive lo>
 Stacktrace:
 locker: cannot acquire lock, already locked
 failed to acquire exclusive lock for power actions
 github.com/pterodactyl/wings/server.(*Server).HandlePowerAction
         /home/runner/work/wings/wings/server/power.go:102
 github.com/pterodactyl/wings/router/websocket.(*Handler).HandleInbound
         /home/runner/work/wings/wings/router/websocket/websocket.go:355
 github.com/pterodactyl/wings/router.getServerWebsocket.func3
         /home/runner/work/wings/wings/router/router_server_ws.go:85
 runtime.goexit
         /opt/hostedtoolcache/go/1.17.6/x64/src/runtime/asm_amd64.s:1581`

**Comment by DaneEveritt** [comment]
@EliteNover @ItsLachy I need the _full_ Wings logs (not the ones from the diagnostics command, it truncates a lot of context), and please indicate at least one server UUID that is facing the issue. I need to be able to see the historical API calls made for the server to better pinpoint consistent reproduction steps.

**Comment by JRH-1997** [comment]
For now in diagnostics format, please let me know how to get the full wings logs: https://ptero.co/otuzejydaz

**Comment by DaneEveritt** [comment]
@JRH-1997 @ItsLachy @EliteNover @iLucasUS

New build with more debugging information based on some other logs I looked at. Doubtful that it fixes the issue yet, but should include better debug output to narrow down the specific action that is failing:

https://github.com/pterodactyl/wings/actions/runs/1775695398

**Comment by liampearson96** [comment]
https://pastebin.com/6zskSUXC

Maybe it will help? Only started happening to me after updating to 1.6.0
Only happens on a single server. with a working schedule. Only happens when the restart schedule is requested.

**Comment by DaneEveritt** [comment]
@liampearson96 your logs appear to have been pasted into a bash prompt? Can you please just pull the file directly, should be somewhere in `/var/log/wings` I believe?

Also, the logs you posted are just Wings failing to start because it is already running.

**Comment by trenutoo** [comment]
`/var/log/pterodactyl/` is the default log path. You can check wings config to see if you have changed it (e.g running wings in docker container)

**Comment by liampearson96** [comment]
[wings.log](https://github.com/pterodactyl/panel/files/7978755/wings.log)

Opps apologies @DaneEveritt this is the only file i have

**Comment by EliteNover** [comment]
Reinstalling the server which has the error fixes it.

**Comment by iLucasUS** [comment]
> A reinstalação do servidor que apresenta o erro o corrige.

This is wrong, I did it on several clients and still the problem came back.

**Comment by DaneEveritt** [comment]
Posting my thoughts from a conversation in Discord:

> I've narrowed down the likely culprit for the power action lock issues.

> But beats me if I know what exactly causes it, just know the consistent lock point for the server logs I've seen.
`server/power.go#onBeforeStart() -> s.SyncWithEnvironment()` (the second call, not the one in s.Sync().
> Somewhere in that function at or after the `s.Environment.InSituUpdate()` call it locks up and never completes.
> The `updating server configuration files...` debug output never shows up. So there are still a few potential spots, but it is definitely narrowed down

> And given the changes we've been making, curious if there is some race/unexpected lockup in the `PublishConsoleOutputFromDaemon` call which would flow through those channels, which might explain the sudden increase in issues stemming from those updates. 

> Which, looking at the code again, seems entirely possible to lock up since the logic in `events/events.go#L114` doesn't account for a blocked channel, and will spin.

**Comment by Techout592** [comment]
Well, just happened to me *again*, here's logs: https://ptero.co/dihubyluse

**Comment by YTRemRem** [comment]
Don't know if this issue have been mentioned, the time of the container show in the panel is freeze 
![image](https://user-images.githubusercontent.com/43708359/152139686-2cc4e200-2054-41f4-8a2c-f4a909a4223f.png)

**Comment by DaneEveritt** [comment]
Please try giving the build from this run a go on your machines: https://github.com/pterodactyl/wings/actions/runs/1787260301

This should resolve the power lock issue assuming I debugged any of this correctly.

**Comment by SMGoro** [comment]
wings version: 1.6.0
https://ptero.co/culazaceru

**Comment by JRH-1997** [comment]
```
DEBUG: [Feb  4 17:02:10.259] acquiring power action lock for instance action=restart lock_id=30f960bb-85dc-11ec-92b1-fa163e54e6d6 server=040ae464-92c1-4ca6-91d3-5bd599961619 wait_seconds=0
 INFO: [Feb  4 17:02:10.260] acquired exclusive lock on power actions, processing event... action=restart lock_id=30f960bb-85dc-11ec-92b1-fa163e54e6d6 server=040ae464-92c1-4ca6-91d3-5bd599961619
DEBUG: [Feb  4 17:02:10.264] saw server status change event server=040ae464-92c1-4ca6-91d3-5bd599961619 status=stopping
DEBUG: [Feb  4 17:02:11.891] GET /api/system client_ip={redacted} latency=84.185µs request_id=9f1a8a60-3937-4279-b2f3-eadef1c3f8f2 status=200
DEBUG: [Feb  4 17:02:15.426] acquiring power action lock for instance action=stop lock_id=340dd9ab-85dc-11ec-92b1-fa163e54e6d6 server=040ae464-92c1-4ca6-91d3-5bd599961619 wait_seconds=0
ERROR: [Feb  4 17:02:15.429] error processing websocket event "set state" error=failed to acquire exclusive lock for power actions: locker: cannot acquire lock, already locked error_identifier=1108bf09-a170-440b-902e-dce501e0df24 event=set state server=040ae464-92c1-4ca6-91d3-5bd599961619

Stacktrace:
locker: cannot acquire lock, already locked
failed to acquire exclusive lock for power actions
github.com/pterodactyl/wings/server.(*Server).HandlePowerAction
	/home/runner/work/wings/wings/server/power.go:102
github.com/pterodactyl/wings/router/websocket.(*Handler).HandleInbound
	/home/runner/work/wings/wings/router/websocket/websocket.go:355
github.com/pterodactyl/wings/router.getServerWebsocket.func3
	/home/runner/work/wings/wings/router/router_server_ws.go:85
runtime.goexit
	/opt/hostedtoolcache/go/1.17.6/x64/src/runtime/asm_amd64.s:1581
```

I've seen this multiple times in our logs now. Restart action that tries to stop the server, but can't stop because of the running process (discord bot). After that the stop command.  But that button should be hidden on the panel when you used the restart command and only show the kill button. 

We don't use the new update but don't know if you fixed this already or if this could help.

**Comment by DaneEveritt** [comment]
Please use the build I linked immediately above. I already know it is broken on existing releases, so additional reports don't help too much. Knowing if it is fixed in the unreleased build is more helpful. :)

**Comment by TsjipTsjip** [comment]
I have switched to the dev build generated from commit 72476c61ec0ede8adff243522b562b8f02935d1e (as instructed in the post immediately above) and can report that the issue appears fixed currently, immediately after switching. I'll edit this post should that changed.

**Comment by itsnotrin** [comment]
I downloaded and installed Dane's new build (https://github.com/pterodactyl/wings/actions/runs/1787260301) and it seems the issue may have stopped. Great work!

**Comment by camwhi-te** [comment]
72476c has fixed all power lock issues for me - looks good!

**Comment by DaneEveritt** [comment]
closed in https://github.com/pterodactyl/wings/commit/72476c61ec0ede8adff243522b562b8f02935d1e

**Comment by RTK23-dev** [comment]
The power lock issue still exists.
I got an error "This server is in a failed install state and cannot be recovered. Please delete and re-create the server." And the wings logs states there is power lock issue and in support server the bot said to update wings, however I am on latest wings version still I updated and ofcourse I restarted wings before and after but the issue still remains.  Heres the wings logs -
https://ptero.co/wililacime

**Comment by Brandin** [comment]
I’m fairly confident the issue you’re describing is not the same as this post.

**Comment by nackerr** [comment]
> The power lock issue still exists.
> I got an error "This server is in a failed install state and cannot be recovered. Please delete and re-create the server." And the wings logs states there is power lock issue and in support server the bot said to update wings, however I am on latest wings version still I updated and ofcourse I restarted wings before and after but the issue still remains. Heres the wings logs -
> https://ptero.co/wililacime

We’ve also been getting this. It’s an issue, but not this issue. It’s not related to the power lock.

**Comment by NaySurGithub** [comment]
stfu dane
